version: '3'
services:
  spring-boot-app:
    image: sjerbi3/spring:latest
    container_name: spring
    ports:
      - "8089:8089"
    networks:
      - project

  database:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: devops
    networks:
      - project

networks:
  project:
